version: "3.6"

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - preaccred_db_data:/var/lib/postgresql/data
    env_file:
      - .env

  graphql-engine:
    image: hasura/graphql-engine:v2.37.0.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./metadata:/hasura-metadata
      - ./migrations:/hasura-migrations
    env_file:
      - .env

volumes:
  preaccred_db_data:
