/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Int_comparison_exp:{

	},
	STATUS_aggregate_fields:{
		count:{
			columns:"STATUS_select_column"
		}
	},
	STATUS_bool_exp:{
		_and:"STATUS_bool_exp",
		_not:"STATUS_bool_exp",
		_or:"STATUS_bool_exp",
		value:"String_comparison_exp"
	},
	STATUS_constraint: "enum" as const,
	STATUS_enum: "enum" as const,
	STATUS_enum_comparison_exp:{
		_eq:"STATUS_enum",
		_in:"STATUS_enum",
		_neq:"STATUS_enum",
		_nin:"STATUS_enum"
	},
	STATUS_insert_input:{

	},
	STATUS_on_conflict:{
		constraint:"STATUS_constraint",
		update_columns:"STATUS_update_column",
		where:"STATUS_bool_exp"
	},
	STATUS_order_by:{
		value:"order_by"
	},
	STATUS_pk_columns_input:{

	},
	STATUS_select_column: "enum" as const,
	STATUS_set_input:{

	},
	STATUS_stream_cursor_input:{
		initial_value:"STATUS_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	STATUS_stream_cursor_value_input:{

	},
	STATUS_update_column: "enum" as const,
	STATUS_updates:{
		_set:"STATUS_set_input",
		where:"STATUS_bool_exp"
	},
	String_comparison_exp:{

	},
	bigint: `scalar.bigint` as const,
	bigint_comparison_exp:{
		_eq:"bigint",
		_gt:"bigint",
		_gte:"bigint",
		_in:"bigint",
		_lt:"bigint",
		_lte:"bigint",
		_neq:"bigint",
		_nin:"bigint"
	},
	cursor_ordering: "enum" as const,
	date: `scalar.date` as const,
	date_comparison_exp:{
		_eq:"date",
		_gt:"date",
		_gte:"date",
		_in:"date",
		_lt:"date",
		_lte:"date",
		_neq:"date",
		_nin:"date"
	},
	e_governance_aggregate_bool_exp:{
		count:"e_governance_aggregate_bool_exp_count"
	},
	e_governance_aggregate_bool_exp_count:{
		arguments:"e_governance_select_column",
		filter:"e_governance_bool_exp",
		predicate:"Int_comparison_exp"
	},
	e_governance_aggregate_fields:{
		count:{
			columns:"e_governance_select_column"
		}
	},
	e_governance_aggregate_order_by:{
		avg:"e_governance_avg_order_by",
		count:"order_by",
		max:"e_governance_max_order_by",
		min:"e_governance_min_order_by",
		stddev:"e_governance_stddev_order_by",
		stddev_pop:"e_governance_stddev_pop_order_by",
		stddev_samp:"e_governance_stddev_samp_order_by",
		sum:"e_governance_sum_order_by",
		var_pop:"e_governance_var_pop_order_by",
		var_samp:"e_governance_var_samp_order_by",
		variance:"e_governance_variance_order_by"
	},
	e_governance_arr_rel_insert_input:{
		data:"e_governance_insert_input",
		on_conflict:"e_governance_on_conflict"
	},
	e_governance_avg_order_by:{
		cursorId:"order_by"
	},
	e_governance_bool_exp:{
		_and:"e_governance_bool_exp",
		_not:"e_governance_bool_exp",
		_or:"e_governance_bool_exp",
		address:"String_comparison_exp",
		area:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		description:"String_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute:"institute_bool_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		phone_no:"String_comparison_exp",
		service_end_date:"date_comparison_exp",
		service_start_date:"date_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		total_amount:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp",
		website:"String_comparison_exp"
	},
	e_governance_constraint: "enum" as const,
	e_governance_inc_input:{
		cursorId:"bigint"
	},
	e_governance_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute:"institute_obj_rel_insert_input",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	e_governance_max_order_by:{
		address:"order_by",
		area:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		description:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		phone_no:"order_by",
		service_end_date:"order_by",
		service_start_date:"order_by",
		total_amount:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		website:"order_by"
	},
	e_governance_min_order_by:{
		address:"order_by",
		area:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		description:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		phone_no:"order_by",
		service_end_date:"order_by",
		service_start_date:"order_by",
		total_amount:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		website:"order_by"
	},
	e_governance_on_conflict:{
		constraint:"e_governance_constraint",
		update_columns:"e_governance_update_column",
		where:"e_governance_bool_exp"
	},
	e_governance_order_by:{
		address:"order_by",
		area:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		description:"order_by",
		file:"order_by",
		id:"order_by",
		institute:"institute_order_by",
		institute_id:"order_by",
		name:"order_by",
		phone_no:"order_by",
		service_end_date:"order_by",
		service_start_date:"order_by",
		status:"order_by",
		total_amount:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		website:"order_by"
	},
	e_governance_pk_columns_input:{
		id:"uuid"
	},
	e_governance_select_column: "enum" as const,
	e_governance_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	e_governance_stddev_order_by:{
		cursorId:"order_by"
	},
	e_governance_stddev_pop_order_by:{
		cursorId:"order_by"
	},
	e_governance_stddev_samp_order_by:{
		cursorId:"order_by"
	},
	e_governance_stream_cursor_input:{
		initial_value:"e_governance_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	e_governance_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	e_governance_sum_order_by:{
		cursorId:"order_by"
	},
	e_governance_update_column: "enum" as const,
	e_governance_updates:{
		_inc:"e_governance_inc_input",
		_set:"e_governance_set_input",
		where:"e_governance_bool_exp"
	},
	e_governance_var_pop_order_by:{
		cursorId:"order_by"
	},
	e_governance_var_samp_order_by:{
		cursorId:"order_by"
	},
	e_governance_variance_order_by:{
		cursorId:"order_by"
	},
	faculty:{
		faculty_fundings:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_fundings_aggregate:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		fdp_pdps:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdps_aggregate:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		}
	},
	faculty_aggregate_bool_exp:{
		count:"faculty_aggregate_bool_exp_count"
	},
	faculty_aggregate_bool_exp_count:{
		arguments:"faculty_select_column",
		filter:"faculty_bool_exp",
		predicate:"Int_comparison_exp"
	},
	faculty_aggregate_fields:{
		count:{
			columns:"faculty_select_column"
		}
	},
	faculty_aggregate_order_by:{
		avg:"faculty_avg_order_by",
		count:"order_by",
		max:"faculty_max_order_by",
		min:"faculty_min_order_by",
		stddev:"faculty_stddev_order_by",
		stddev_pop:"faculty_stddev_pop_order_by",
		stddev_samp:"faculty_stddev_samp_order_by",
		sum:"faculty_sum_order_by",
		var_pop:"faculty_var_pop_order_by",
		var_samp:"faculty_var_samp_order_by",
		variance:"faculty_variance_order_by"
	},
	faculty_arr_rel_insert_input:{
		data:"faculty_insert_input",
		on_conflict:"faculty_on_conflict"
	},
	faculty_avg_order_by:{
		cursorId:"order_by"
	},
	faculty_bool_exp:{
		_and:"faculty_bool_exp",
		_not:"faculty_bool_exp",
		_or:"faculty_bool_exp",
		address:"String_comparison_exp",
		cast:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		date_of_joining:"date_comparison_exp",
		designation:"String_comparison_exp",
		dob:"date_comparison_exp",
		email_id:"String_comparison_exp",
		experience:"String_comparison_exp",
		faculty_fundings:"faculty_funding_bool_exp",
		faculty_fundings_aggregate:"faculty_funding_aggregate_bool_exp",
		fdp_pdps:"fdp_pdp_bool_exp",
		fdp_pdps_aggregate:"fdp_pdp_aggregate_bool_exp",
		gender:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute:"institute_bool_exp",
		institute_id:"uuid_comparison_exp",
		job_type:"String_comparison_exp",
		minority:"String_comparison_exp",
		name:"String_comparison_exp",
		pan_card_no:"String_comparison_exp",
		phone:"String_comparison_exp",
		qualification:"String_comparison_exp",
		section:"String_comparison_exp",
		staff_type:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		status_of_approval:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp"
	},
	faculty_constraint: "enum" as const,
	faculty_funding_aggregate_bool_exp:{
		count:"faculty_funding_aggregate_bool_exp_count"
	},
	faculty_funding_aggregate_bool_exp_count:{
		arguments:"faculty_funding_select_column",
		filter:"faculty_funding_bool_exp",
		predicate:"Int_comparison_exp"
	},
	faculty_funding_aggregate_fields:{
		count:{
			columns:"faculty_funding_select_column"
		}
	},
	faculty_funding_aggregate_order_by:{
		avg:"faculty_funding_avg_order_by",
		count:"order_by",
		max:"faculty_funding_max_order_by",
		min:"faculty_funding_min_order_by",
		stddev:"faculty_funding_stddev_order_by",
		stddev_pop:"faculty_funding_stddev_pop_order_by",
		stddev_samp:"faculty_funding_stddev_samp_order_by",
		sum:"faculty_funding_sum_order_by",
		var_pop:"faculty_funding_var_pop_order_by",
		var_samp:"faculty_funding_var_samp_order_by",
		variance:"faculty_funding_variance_order_by"
	},
	faculty_funding_arr_rel_insert_input:{
		data:"faculty_funding_insert_input",
		on_conflict:"faculty_funding_on_conflict"
	},
	faculty_funding_avg_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_bool_exp:{
		_and:"faculty_funding_bool_exp",
		_not:"faculty_funding_bool_exp",
		_or:"faculty_funding_bool_exp",
		amount:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		faculty:"faculty_bool_exp",
		faculty_id:"uuid_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute:"institute_bool_exp",
		institute_id:"uuid_comparison_exp",
		nature:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		transaction_date:"date_comparison_exp",
		transaction_type:"String_comparison_exp",
		type:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp"
	},
	faculty_funding_constraint: "enum" as const,
	faculty_funding_inc_input:{
		cursorId:"bigint"
	},
	faculty_funding_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty:"faculty_obj_rel_insert_input",
		faculty_id:"uuid",
		id:"uuid",
		institute:"institute_obj_rel_insert_input",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_max_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		nature:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_funding_min_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		nature:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_funding_on_conflict:{
		constraint:"faculty_funding_constraint",
		update_columns:"faculty_funding_update_column",
		where:"faculty_funding_bool_exp"
	},
	faculty_funding_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		faculty:"faculty_order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute:"institute_order_by",
		institute_id:"order_by",
		nature:"order_by",
		status:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_funding_pk_columns_input:{
		id:"uuid"
	},
	faculty_funding_select_column: "enum" as const,
	faculty_funding_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_stddev_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_stddev_pop_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_stddev_samp_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_stream_cursor_input:{
		initial_value:"faculty_funding_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	faculty_funding_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_sum_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_update_column: "enum" as const,
	faculty_funding_updates:{
		_inc:"faculty_funding_inc_input",
		_set:"faculty_funding_set_input",
		where:"faculty_funding_bool_exp"
	},
	faculty_funding_var_pop_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_var_samp_order_by:{
		cursorId:"order_by"
	},
	faculty_funding_variance_order_by:{
		cursorId:"order_by"
	},
	faculty_inc_input:{
		cursorId:"bigint"
	},
	faculty_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		dob:"date",
		faculty_fundings:"faculty_funding_arr_rel_insert_input",
		fdp_pdps:"fdp_pdp_arr_rel_insert_input",
		id:"uuid",
		institute:"institute_obj_rel_insert_input",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_max_order_by:{
		address:"order_by",
		cast:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_of_joining:"order_by",
		designation:"order_by",
		dob:"order_by",
		email_id:"order_by",
		experience:"order_by",
		gender:"order_by",
		id:"order_by",
		institute_id:"order_by",
		job_type:"order_by",
		minority:"order_by",
		name:"order_by",
		pan_card_no:"order_by",
		phone:"order_by",
		qualification:"order_by",
		section:"order_by",
		staff_type:"order_by",
		status_of_approval:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_min_order_by:{
		address:"order_by",
		cast:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_of_joining:"order_by",
		designation:"order_by",
		dob:"order_by",
		email_id:"order_by",
		experience:"order_by",
		gender:"order_by",
		id:"order_by",
		institute_id:"order_by",
		job_type:"order_by",
		minority:"order_by",
		name:"order_by",
		pan_card_no:"order_by",
		phone:"order_by",
		qualification:"order_by",
		section:"order_by",
		staff_type:"order_by",
		status_of_approval:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_obj_rel_insert_input:{
		data:"faculty_insert_input",
		on_conflict:"faculty_on_conflict"
	},
	faculty_on_conflict:{
		constraint:"faculty_constraint",
		update_columns:"faculty_update_column",
		where:"faculty_bool_exp"
	},
	faculty_order_by:{
		address:"order_by",
		cast:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_of_joining:"order_by",
		designation:"order_by",
		dob:"order_by",
		email_id:"order_by",
		experience:"order_by",
		faculty_fundings_aggregate:"faculty_funding_aggregate_order_by",
		fdp_pdps_aggregate:"fdp_pdp_aggregate_order_by",
		gender:"order_by",
		id:"order_by",
		institute:"institute_order_by",
		institute_id:"order_by",
		job_type:"order_by",
		minority:"order_by",
		name:"order_by",
		pan_card_no:"order_by",
		phone:"order_by",
		qualification:"order_by",
		section:"order_by",
		staff_type:"order_by",
		status:"order_by",
		status_of_approval:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	faculty_pk_columns_input:{
		id:"uuid"
	},
	faculty_select_column: "enum" as const,
	faculty_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		dob:"date",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_stddev_order_by:{
		cursorId:"order_by"
	},
	faculty_stddev_pop_order_by:{
		cursorId:"order_by"
	},
	faculty_stddev_samp_order_by:{
		cursorId:"order_by"
	},
	faculty_stream_cursor_input:{
		initial_value:"faculty_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	faculty_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		dob:"date",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_sum_order_by:{
		cursorId:"order_by"
	},
	faculty_update_column: "enum" as const,
	faculty_updates:{
		_inc:"faculty_inc_input",
		_set:"faculty_set_input",
		where:"faculty_bool_exp"
	},
	faculty_var_pop_order_by:{
		cursorId:"order_by"
	},
	faculty_var_samp_order_by:{
		cursorId:"order_by"
	},
	faculty_variance_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_aggregate_bool_exp:{
		count:"fdp_pdp_aggregate_bool_exp_count"
	},
	fdp_pdp_aggregate_bool_exp_count:{
		arguments:"fdp_pdp_select_column",
		filter:"fdp_pdp_bool_exp",
		predicate:"Int_comparison_exp"
	},
	fdp_pdp_aggregate_fields:{
		count:{
			columns:"fdp_pdp_select_column"
		}
	},
	fdp_pdp_aggregate_order_by:{
		avg:"fdp_pdp_avg_order_by",
		count:"order_by",
		max:"fdp_pdp_max_order_by",
		min:"fdp_pdp_min_order_by",
		stddev:"fdp_pdp_stddev_order_by",
		stddev_pop:"fdp_pdp_stddev_pop_order_by",
		stddev_samp:"fdp_pdp_stddev_samp_order_by",
		sum:"fdp_pdp_sum_order_by",
		var_pop:"fdp_pdp_var_pop_order_by",
		var_samp:"fdp_pdp_var_samp_order_by",
		variance:"fdp_pdp_variance_order_by"
	},
	fdp_pdp_arr_rel_insert_input:{
		data:"fdp_pdp_insert_input",
		on_conflict:"fdp_pdp_on_conflict"
	},
	fdp_pdp_avg_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_bool_exp:{
		_and:"fdp_pdp_bool_exp",
		_not:"fdp_pdp_bool_exp",
		_or:"fdp_pdp_bool_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		date_from:"date_comparison_exp",
		date_to:"date_comparison_exp",
		description:"String_comparison_exp",
		faculty:"faculty_bool_exp",
		faculty_id:"uuid_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute:"institute_bool_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		nature:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		type:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp",
		venue:"String_comparison_exp"
	},
	fdp_pdp_constraint: "enum" as const,
	fdp_pdp_inc_input:{
		cursorId:"bigint"
	},
	fdp_pdp_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		faculty:"faculty_obj_rel_insert_input",
		faculty_id:"uuid",
		id:"uuid",
		institute:"institute_obj_rel_insert_input",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	fdp_pdp_max_order_by:{
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_from:"order_by",
		date_to:"order_by",
		description:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		nature:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		venue:"order_by"
	},
	fdp_pdp_min_order_by:{
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_from:"order_by",
		date_to:"order_by",
		description:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		nature:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		venue:"order_by"
	},
	fdp_pdp_on_conflict:{
		constraint:"fdp_pdp_constraint",
		update_columns:"fdp_pdp_update_column",
		where:"fdp_pdp_bool_exp"
	},
	fdp_pdp_order_by:{
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_from:"order_by",
		date_to:"order_by",
		description:"order_by",
		faculty:"faculty_order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute:"institute_order_by",
		institute_id:"order_by",
		name:"order_by",
		nature:"order_by",
		status:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		venue:"order_by"
	},
	fdp_pdp_pk_columns_input:{
		id:"uuid"
	},
	fdp_pdp_select_column: "enum" as const,
	fdp_pdp_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	fdp_pdp_stddev_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_stddev_pop_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_stddev_samp_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_stream_cursor_input:{
		initial_value:"fdp_pdp_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	fdp_pdp_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	fdp_pdp_sum_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_update_column: "enum" as const,
	fdp_pdp_updates:{
		_inc:"fdp_pdp_inc_input",
		_set:"fdp_pdp_set_input",
		where:"fdp_pdp_bool_exp"
	},
	fdp_pdp_var_pop_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_var_samp_order_by:{
		cursorId:"order_by"
	},
	fdp_pdp_variance_order_by:{
		cursorId:"order_by"
	},
	genesis_aggregate_fields:{
		count:{
			columns:"genesis_select_column"
		}
	},
	genesis_bool_exp:{
		_and:"genesis_bool_exp",
		_not:"genesis_bool_exp",
		_or:"genesis_bool_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		email_id:"String_comparison_exp",
		id:"uuid_comparison_exp",
		isVerified:"String_comparison_exp",
		name:"String_comparison_exp",
		phone:"String_comparison_exp",
		role:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp"
	},
	genesis_constraint: "enum" as const,
	genesis_inc_input:{
		cursorId:"bigint"
	},
	genesis_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_on_conflict:{
		constraint:"genesis_constraint",
		update_columns:"genesis_update_column",
		where:"genesis_bool_exp"
	},
	genesis_order_by:{
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		email_id:"order_by",
		id:"order_by",
		isVerified:"order_by",
		name:"order_by",
		phone:"order_by",
		role:"order_by",
		status:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	genesis_pk_columns_input:{
		id:"uuid"
	},
	genesis_select_column: "enum" as const,
	genesis_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_stream_cursor_input:{
		initial_value:"genesis_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	genesis_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_update_column: "enum" as const,
	genesis_updates:{
		_inc:"genesis_inc_input",
		_set:"genesis_set_input",
		where:"genesis_bool_exp"
	},
	institute:{
		e_governances:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		e_governances_aggregate:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		faculties:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculties_aggregate:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculty_fundings:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_fundings_aggregate:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		fdp_pdps:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdps_aggregate:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		institute_fundings:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		},
		institute_fundings_aggregate:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		}
	},
	institute_aggregate_fields:{
		count:{
			columns:"institute_select_column"
		}
	},
	institute_bool_exp:{
		_and:"institute_bool_exp",
		_not:"institute_bool_exp",
		_or:"institute_bool_exp",
		address:"String_comparison_exp",
		city:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		date_of_establishment:"date_comparison_exp",
		e_governances:"e_governance_bool_exp",
		e_governances_aggregate:"e_governance_aggregate_bool_exp",
		faculties:"faculty_bool_exp",
		faculties_aggregate:"faculty_aggregate_bool_exp",
		faculty_fundings:"faculty_funding_bool_exp",
		faculty_fundings_aggregate:"faculty_funding_aggregate_bool_exp",
		fdp_pdps:"fdp_pdp_bool_exp",
		fdp_pdps_aggregate:"fdp_pdp_aggregate_bool_exp",
		id:"uuid_comparison_exp",
		institute_fundings:"institute_funding_bool_exp",
		institute_fundings_aggregate:"institute_funding_aggregate_bool_exp",
		landmark:"String_comparison_exp",
		name:"String_comparison_exp",
		pin:"String_comparison_exp",
		state:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		type:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp",
		website:"String_comparison_exp"
	},
	institute_constraint: "enum" as const,
	institute_funding_aggregate_bool_exp:{
		count:"institute_funding_aggregate_bool_exp_count"
	},
	institute_funding_aggregate_bool_exp_count:{
		arguments:"institute_funding_select_column",
		filter:"institute_funding_bool_exp",
		predicate:"Int_comparison_exp"
	},
	institute_funding_aggregate_fields:{
		count:{
			columns:"institute_funding_select_column"
		}
	},
	institute_funding_aggregate_order_by:{
		avg:"institute_funding_avg_order_by",
		count:"order_by",
		max:"institute_funding_max_order_by",
		min:"institute_funding_min_order_by",
		stddev:"institute_funding_stddev_order_by",
		stddev_pop:"institute_funding_stddev_pop_order_by",
		stddev_samp:"institute_funding_stddev_samp_order_by",
		sum:"institute_funding_sum_order_by",
		var_pop:"institute_funding_var_pop_order_by",
		var_samp:"institute_funding_var_samp_order_by",
		variance:"institute_funding_variance_order_by"
	},
	institute_funding_arr_rel_insert_input:{
		data:"institute_funding_insert_input",
		on_conflict:"institute_funding_on_conflict"
	},
	institute_funding_avg_order_by:{
		cursorId:"order_by"
	},
	institute_funding_bool_exp:{
		_and:"institute_funding_bool_exp",
		_not:"institute_funding_bool_exp",
		_or:"institute_funding_bool_exp",
		amount:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		createdById:"uuid_comparison_exp",
		cursorId:"bigint_comparison_exp",
		id:"uuid_comparison_exp",
		institute:"institute_bool_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		purpose:"String_comparison_exp",
		status:"STATUS_enum_comparison_exp",
		transaction_date:"date_comparison_exp",
		transaction_type:"String_comparison_exp",
		type:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		updatedById:"uuid_comparison_exp"
	},
	institute_funding_constraint: "enum" as const,
	institute_funding_inc_input:{
		cursorId:"bigint"
	},
	institute_funding_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute:"institute_obj_rel_insert_input",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_max_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		purpose:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	institute_funding_min_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		purpose:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	institute_funding_on_conflict:{
		constraint:"institute_funding_constraint",
		update_columns:"institute_funding_update_column",
		where:"institute_funding_bool_exp"
	},
	institute_funding_order_by:{
		amount:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		id:"order_by",
		institute:"institute_order_by",
		institute_id:"order_by",
		name:"order_by",
		purpose:"order_by",
		status:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by"
	},
	institute_funding_pk_columns_input:{
		id:"uuid"
	},
	institute_funding_select_column: "enum" as const,
	institute_funding_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_stddev_order_by:{
		cursorId:"order_by"
	},
	institute_funding_stddev_pop_order_by:{
		cursorId:"order_by"
	},
	institute_funding_stddev_samp_order_by:{
		cursorId:"order_by"
	},
	institute_funding_stream_cursor_input:{
		initial_value:"institute_funding_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	institute_funding_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		status:"STATUS_enum",
		transaction_date:"date",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_sum_order_by:{
		cursorId:"order_by"
	},
	institute_funding_update_column: "enum" as const,
	institute_funding_updates:{
		_inc:"institute_funding_inc_input",
		_set:"institute_funding_set_input",
		where:"institute_funding_bool_exp"
	},
	institute_funding_var_pop_order_by:{
		cursorId:"order_by"
	},
	institute_funding_var_samp_order_by:{
		cursorId:"order_by"
	},
	institute_funding_variance_order_by:{
		cursorId:"order_by"
	},
	institute_inc_input:{
		cursorId:"bigint"
	},
	institute_insert_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		e_governances:"e_governance_arr_rel_insert_input",
		faculties:"faculty_arr_rel_insert_input",
		faculty_fundings:"faculty_funding_arr_rel_insert_input",
		fdp_pdps:"fdp_pdp_arr_rel_insert_input",
		id:"uuid",
		institute_fundings:"institute_funding_arr_rel_insert_input",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_obj_rel_insert_input:{
		data:"institute_insert_input",
		on_conflict:"institute_on_conflict"
	},
	institute_on_conflict:{
		constraint:"institute_constraint",
		update_columns:"institute_update_column",
		where:"institute_bool_exp"
	},
	institute_order_by:{
		address:"order_by",
		city:"order_by",
		createdAt:"order_by",
		createdById:"order_by",
		cursorId:"order_by",
		date_of_establishment:"order_by",
		e_governances_aggregate:"e_governance_aggregate_order_by",
		faculties_aggregate:"faculty_aggregate_order_by",
		faculty_fundings_aggregate:"faculty_funding_aggregate_order_by",
		fdp_pdps_aggregate:"fdp_pdp_aggregate_order_by",
		id:"order_by",
		institute_fundings_aggregate:"institute_funding_aggregate_order_by",
		landmark:"order_by",
		name:"order_by",
		pin:"order_by",
		state:"order_by",
		status:"order_by",
		type:"order_by",
		updatedAt:"order_by",
		updatedById:"order_by",
		website:"order_by"
	},
	institute_pk_columns_input:{
		id:"uuid"
	},
	institute_select_column: "enum" as const,
	institute_set_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_stream_cursor_input:{
		initial_value:"institute_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	institute_stream_cursor_value_input:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		id:"uuid",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_update_column: "enum" as const,
	institute_updates:{
		_inc:"institute_inc_input",
		_set:"institute_set_input",
		where:"institute_bool_exp"
	},
	mutation_root:{
		delete_STATUS:{
			where:"STATUS_bool_exp"
		},
		delete_STATUS_by_pk:{

		},
		delete_e_governance:{
			where:"e_governance_bool_exp"
		},
		delete_e_governance_by_pk:{
			id:"uuid"
		},
		delete_faculty:{
			where:"faculty_bool_exp"
		},
		delete_faculty_by_pk:{
			id:"uuid"
		},
		delete_faculty_funding:{
			where:"faculty_funding_bool_exp"
		},
		delete_faculty_funding_by_pk:{
			id:"uuid"
		},
		delete_fdp_pdp:{
			where:"fdp_pdp_bool_exp"
		},
		delete_fdp_pdp_by_pk:{
			id:"uuid"
		},
		delete_genesis:{
			where:"genesis_bool_exp"
		},
		delete_genesis_by_pk:{
			id:"uuid"
		},
		delete_institute:{
			where:"institute_bool_exp"
		},
		delete_institute_by_pk:{
			id:"uuid"
		},
		delete_institute_funding:{
			where:"institute_funding_bool_exp"
		},
		delete_institute_funding_by_pk:{
			id:"uuid"
		},
		insert_STATUS:{
			objects:"STATUS_insert_input",
			on_conflict:"STATUS_on_conflict"
		},
		insert_STATUS_one:{
			object:"STATUS_insert_input",
			on_conflict:"STATUS_on_conflict"
		},
		insert_e_governance:{
			objects:"e_governance_insert_input",
			on_conflict:"e_governance_on_conflict"
		},
		insert_e_governance_one:{
			object:"e_governance_insert_input",
			on_conflict:"e_governance_on_conflict"
		},
		insert_faculty:{
			objects:"faculty_insert_input",
			on_conflict:"faculty_on_conflict"
		},
		insert_faculty_funding:{
			objects:"faculty_funding_insert_input",
			on_conflict:"faculty_funding_on_conflict"
		},
		insert_faculty_funding_one:{
			object:"faculty_funding_insert_input",
			on_conflict:"faculty_funding_on_conflict"
		},
		insert_faculty_one:{
			object:"faculty_insert_input",
			on_conflict:"faculty_on_conflict"
		},
		insert_fdp_pdp:{
			objects:"fdp_pdp_insert_input",
			on_conflict:"fdp_pdp_on_conflict"
		},
		insert_fdp_pdp_one:{
			object:"fdp_pdp_insert_input",
			on_conflict:"fdp_pdp_on_conflict"
		},
		insert_genesis:{
			objects:"genesis_insert_input",
			on_conflict:"genesis_on_conflict"
		},
		insert_genesis_one:{
			object:"genesis_insert_input",
			on_conflict:"genesis_on_conflict"
		},
		insert_institute:{
			objects:"institute_insert_input",
			on_conflict:"institute_on_conflict"
		},
		insert_institute_funding:{
			objects:"institute_funding_insert_input",
			on_conflict:"institute_funding_on_conflict"
		},
		insert_institute_funding_one:{
			object:"institute_funding_insert_input",
			on_conflict:"institute_funding_on_conflict"
		},
		insert_institute_one:{
			object:"institute_insert_input",
			on_conflict:"institute_on_conflict"
		},
		update_STATUS:{
			_set:"STATUS_set_input",
			where:"STATUS_bool_exp"
		},
		update_STATUS_by_pk:{
			_set:"STATUS_set_input",
			pk_columns:"STATUS_pk_columns_input"
		},
		update_STATUS_many:{
			updates:"STATUS_updates"
		},
		update_e_governance:{
			_inc:"e_governance_inc_input",
			_set:"e_governance_set_input",
			where:"e_governance_bool_exp"
		},
		update_e_governance_by_pk:{
			_inc:"e_governance_inc_input",
			_set:"e_governance_set_input",
			pk_columns:"e_governance_pk_columns_input"
		},
		update_e_governance_many:{
			updates:"e_governance_updates"
		},
		update_faculty:{
			_inc:"faculty_inc_input",
			_set:"faculty_set_input",
			where:"faculty_bool_exp"
		},
		update_faculty_by_pk:{
			_inc:"faculty_inc_input",
			_set:"faculty_set_input",
			pk_columns:"faculty_pk_columns_input"
		},
		update_faculty_funding:{
			_inc:"faculty_funding_inc_input",
			_set:"faculty_funding_set_input",
			where:"faculty_funding_bool_exp"
		},
		update_faculty_funding_by_pk:{
			_inc:"faculty_funding_inc_input",
			_set:"faculty_funding_set_input",
			pk_columns:"faculty_funding_pk_columns_input"
		},
		update_faculty_funding_many:{
			updates:"faculty_funding_updates"
		},
		update_faculty_many:{
			updates:"faculty_updates"
		},
		update_fdp_pdp:{
			_inc:"fdp_pdp_inc_input",
			_set:"fdp_pdp_set_input",
			where:"fdp_pdp_bool_exp"
		},
		update_fdp_pdp_by_pk:{
			_inc:"fdp_pdp_inc_input",
			_set:"fdp_pdp_set_input",
			pk_columns:"fdp_pdp_pk_columns_input"
		},
		update_fdp_pdp_many:{
			updates:"fdp_pdp_updates"
		},
		update_genesis:{
			_inc:"genesis_inc_input",
			_set:"genesis_set_input",
			where:"genesis_bool_exp"
		},
		update_genesis_by_pk:{
			_inc:"genesis_inc_input",
			_set:"genesis_set_input",
			pk_columns:"genesis_pk_columns_input"
		},
		update_genesis_many:{
			updates:"genesis_updates"
		},
		update_institute:{
			_inc:"institute_inc_input",
			_set:"institute_set_input",
			where:"institute_bool_exp"
		},
		update_institute_by_pk:{
			_inc:"institute_inc_input",
			_set:"institute_set_input",
			pk_columns:"institute_pk_columns_input"
		},
		update_institute_funding:{
			_inc:"institute_funding_inc_input",
			_set:"institute_funding_set_input",
			where:"institute_funding_bool_exp"
		},
		update_institute_funding_by_pk:{
			_inc:"institute_funding_inc_input",
			_set:"institute_funding_set_input",
			pk_columns:"institute_funding_pk_columns_input"
		},
		update_institute_funding_many:{
			updates:"institute_funding_updates"
		},
		update_institute_many:{
			updates:"institute_updates"
		}
	},
	order_by: "enum" as const,
	query_root:{
		STATUS:{
			distinct_on:"STATUS_select_column",
			order_by:"STATUS_order_by",
			where:"STATUS_bool_exp"
		},
		STATUS_aggregate:{
			distinct_on:"STATUS_select_column",
			order_by:"STATUS_order_by",
			where:"STATUS_bool_exp"
		},
		STATUS_by_pk:{

		},
		e_governance:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		e_governance_aggregate:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		e_governance_by_pk:{
			id:"uuid"
		},
		faculty:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculty_aggregate:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculty_by_pk:{
			id:"uuid"
		},
		faculty_funding:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_funding_aggregate:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_funding_by_pk:{
			id:"uuid"
		},
		fdp_pdp:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdp_aggregate:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdp_by_pk:{
			id:"uuid"
		},
		genesis:{
			distinct_on:"genesis_select_column",
			order_by:"genesis_order_by",
			where:"genesis_bool_exp"
		},
		genesis_aggregate:{
			distinct_on:"genesis_select_column",
			order_by:"genesis_order_by",
			where:"genesis_bool_exp"
		},
		genesis_by_pk:{
			id:"uuid"
		},
		institute:{
			distinct_on:"institute_select_column",
			order_by:"institute_order_by",
			where:"institute_bool_exp"
		},
		institute_aggregate:{
			distinct_on:"institute_select_column",
			order_by:"institute_order_by",
			where:"institute_bool_exp"
		},
		institute_by_pk:{
			id:"uuid"
		},
		institute_funding:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		},
		institute_funding_aggregate:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		},
		institute_funding_by_pk:{
			id:"uuid"
		}
	},
	subscription_root:{
		STATUS:{
			distinct_on:"STATUS_select_column",
			order_by:"STATUS_order_by",
			where:"STATUS_bool_exp"
		},
		STATUS_aggregate:{
			distinct_on:"STATUS_select_column",
			order_by:"STATUS_order_by",
			where:"STATUS_bool_exp"
		},
		STATUS_by_pk:{

		},
		STATUS_stream:{
			cursor:"STATUS_stream_cursor_input",
			where:"STATUS_bool_exp"
		},
		e_governance:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		e_governance_aggregate:{
			distinct_on:"e_governance_select_column",
			order_by:"e_governance_order_by",
			where:"e_governance_bool_exp"
		},
		e_governance_by_pk:{
			id:"uuid"
		},
		e_governance_stream:{
			cursor:"e_governance_stream_cursor_input",
			where:"e_governance_bool_exp"
		},
		faculty:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculty_aggregate:{
			distinct_on:"faculty_select_column",
			order_by:"faculty_order_by",
			where:"faculty_bool_exp"
		},
		faculty_by_pk:{
			id:"uuid"
		},
		faculty_funding:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_funding_aggregate:{
			distinct_on:"faculty_funding_select_column",
			order_by:"faculty_funding_order_by",
			where:"faculty_funding_bool_exp"
		},
		faculty_funding_by_pk:{
			id:"uuid"
		},
		faculty_funding_stream:{
			cursor:"faculty_funding_stream_cursor_input",
			where:"faculty_funding_bool_exp"
		},
		faculty_stream:{
			cursor:"faculty_stream_cursor_input",
			where:"faculty_bool_exp"
		},
		fdp_pdp:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdp_aggregate:{
			distinct_on:"fdp_pdp_select_column",
			order_by:"fdp_pdp_order_by",
			where:"fdp_pdp_bool_exp"
		},
		fdp_pdp_by_pk:{
			id:"uuid"
		},
		fdp_pdp_stream:{
			cursor:"fdp_pdp_stream_cursor_input",
			where:"fdp_pdp_bool_exp"
		},
		genesis:{
			distinct_on:"genesis_select_column",
			order_by:"genesis_order_by",
			where:"genesis_bool_exp"
		},
		genesis_aggregate:{
			distinct_on:"genesis_select_column",
			order_by:"genesis_order_by",
			where:"genesis_bool_exp"
		},
		genesis_by_pk:{
			id:"uuid"
		},
		genesis_stream:{
			cursor:"genesis_stream_cursor_input",
			where:"genesis_bool_exp"
		},
		institute:{
			distinct_on:"institute_select_column",
			order_by:"institute_order_by",
			where:"institute_bool_exp"
		},
		institute_aggregate:{
			distinct_on:"institute_select_column",
			order_by:"institute_order_by",
			where:"institute_bool_exp"
		},
		institute_by_pk:{
			id:"uuid"
		},
		institute_funding:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		},
		institute_funding_aggregate:{
			distinct_on:"institute_funding_select_column",
			order_by:"institute_funding_order_by",
			where:"institute_funding_bool_exp"
		},
		institute_funding_by_pk:{
			id:"uuid"
		},
		institute_funding_stream:{
			cursor:"institute_funding_stream_cursor_input",
			where:"institute_funding_bool_exp"
		},
		institute_stream:{
			cursor:"institute_stream_cursor_input",
			where:"institute_bool_exp"
		}
	},
	timestamptz: `scalar.timestamptz` as const,
	timestamptz_comparison_exp:{
		_eq:"timestamptz",
		_gt:"timestamptz",
		_gte:"timestamptz",
		_in:"timestamptz",
		_lt:"timestamptz",
		_lte:"timestamptz",
		_neq:"timestamptz",
		_nin:"timestamptz"
	},
	uuid: `scalar.uuid` as const,
	uuid_comparison_exp:{
		_eq:"uuid",
		_gt:"uuid",
		_gte:"uuid",
		_in:"uuid",
		_lt:"uuid",
		_lte:"uuid",
		_neq:"uuid",
		_nin:"uuid"
	}
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	STATUS:{
		value:"String"
	},
	STATUS_aggregate:{
		aggregate:"STATUS_aggregate_fields",
		nodes:"STATUS"
	},
	STATUS_aggregate_fields:{
		count:"Int",
		max:"STATUS_max_fields",
		min:"STATUS_min_fields"
	},
	STATUS_max_fields:{
		value:"String"
	},
	STATUS_min_fields:{
		value:"String"
	},
	STATUS_mutation_response:{
		affected_rows:"Int",
		returning:"STATUS"
	},
	bigint: `scalar.bigint` as const,
	date: `scalar.date` as const,
	e_governance:{
		address:"String",
		area:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		description:"String",
		file:"String",
		id:"uuid",
		institute:"institute",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		status:"STATUS_enum",
		total_amount:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	e_governance_aggregate:{
		aggregate:"e_governance_aggregate_fields",
		nodes:"e_governance"
	},
	e_governance_aggregate_fields:{
		avg:"e_governance_avg_fields",
		count:"Int",
		max:"e_governance_max_fields",
		min:"e_governance_min_fields",
		stddev:"e_governance_stddev_fields",
		stddev_pop:"e_governance_stddev_pop_fields",
		stddev_samp:"e_governance_stddev_samp_fields",
		sum:"e_governance_sum_fields",
		var_pop:"e_governance_var_pop_fields",
		var_samp:"e_governance_var_samp_fields",
		variance:"e_governance_variance_fields"
	},
	e_governance_avg_fields:{
		cursorId:"Float"
	},
	e_governance_max_fields:{
		address:"String",
		area:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		description:"String",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		total_amount:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	e_governance_min_fields:{
		address:"String",
		area:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		description:"String",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		total_amount:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	e_governance_mutation_response:{
		affected_rows:"Int",
		returning:"e_governance"
	},
	e_governance_stddev_fields:{
		cursorId:"Float"
	},
	e_governance_stddev_pop_fields:{
		cursorId:"Float"
	},
	e_governance_stddev_samp_fields:{
		cursorId:"Float"
	},
	e_governance_sum_fields:{
		cursorId:"bigint"
	},
	e_governance_var_pop_fields:{
		cursorId:"Float"
	},
	e_governance_var_samp_fields:{
		cursorId:"Float"
	},
	e_governance_variance_fields:{
		cursorId:"Float"
	},
	faculty:{
		address:"String",
		cast:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		faculty_fundings:"faculty_funding",
		faculty_fundings_aggregate:"faculty_funding_aggregate",
		fdp_pdps:"fdp_pdp",
		fdp_pdps_aggregate:"fdp_pdp_aggregate",
		gender:"String",
		id:"uuid",
		institute:"institute",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status:"STATUS_enum",
		status_of_approval:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_aggregate:{
		aggregate:"faculty_aggregate_fields",
		nodes:"faculty"
	},
	faculty_aggregate_fields:{
		avg:"faculty_avg_fields",
		count:"Int",
		max:"faculty_max_fields",
		min:"faculty_min_fields",
		stddev:"faculty_stddev_fields",
		stddev_pop:"faculty_stddev_pop_fields",
		stddev_samp:"faculty_stddev_samp_fields",
		sum:"faculty_sum_fields",
		var_pop:"faculty_var_pop_fields",
		var_samp:"faculty_var_samp_fields",
		variance:"faculty_variance_fields"
	},
	faculty_avg_fields:{
		cursorId:"Float"
	},
	faculty_funding:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty:"faculty",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute:"institute",
		institute_id:"uuid",
		nature:"String",
		status:"STATUS_enum",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_aggregate:{
		aggregate:"faculty_funding_aggregate_fields",
		nodes:"faculty_funding"
	},
	faculty_funding_aggregate_fields:{
		avg:"faculty_funding_avg_fields",
		count:"Int",
		max:"faculty_funding_max_fields",
		min:"faculty_funding_min_fields",
		stddev:"faculty_funding_stddev_fields",
		stddev_pop:"faculty_funding_stddev_pop_fields",
		stddev_samp:"faculty_funding_stddev_samp_fields",
		sum:"faculty_funding_sum_fields",
		var_pop:"faculty_funding_var_pop_fields",
		var_samp:"faculty_funding_var_samp_fields",
		variance:"faculty_funding_variance_fields"
	},
	faculty_funding_avg_fields:{
		cursorId:"Float"
	},
	faculty_funding_max_fields:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		nature:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_min_fields:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		nature:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_funding_mutation_response:{
		affected_rows:"Int",
		returning:"faculty_funding"
	},
	faculty_funding_stddev_fields:{
		cursorId:"Float"
	},
	faculty_funding_stddev_pop_fields:{
		cursorId:"Float"
	},
	faculty_funding_stddev_samp_fields:{
		cursorId:"Float"
	},
	faculty_funding_sum_fields:{
		cursorId:"bigint"
	},
	faculty_funding_var_pop_fields:{
		cursorId:"Float"
	},
	faculty_funding_var_samp_fields:{
		cursorId:"Float"
	},
	faculty_funding_variance_fields:{
		cursorId:"Float"
	},
	faculty_max_fields:{
		address:"String",
		cast:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		gender:"String",
		id:"uuid",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status_of_approval:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_min_fields:{
		address:"String",
		cast:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		gender:"String",
		id:"uuid",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status_of_approval:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	faculty_mutation_response:{
		affected_rows:"Int",
		returning:"faculty"
	},
	faculty_stddev_fields:{
		cursorId:"Float"
	},
	faculty_stddev_pop_fields:{
		cursorId:"Float"
	},
	faculty_stddev_samp_fields:{
		cursorId:"Float"
	},
	faculty_sum_fields:{
		cursorId:"bigint"
	},
	faculty_var_pop_fields:{
		cursorId:"Float"
	},
	faculty_var_samp_fields:{
		cursorId:"Float"
	},
	faculty_variance_fields:{
		cursorId:"Float"
	},
	fdp_pdp:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty:"faculty",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute:"institute",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		status:"STATUS_enum",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		venue:"String"
	},
	fdp_pdp_aggregate:{
		aggregate:"fdp_pdp_aggregate_fields",
		nodes:"fdp_pdp"
	},
	fdp_pdp_aggregate_fields:{
		avg:"fdp_pdp_avg_fields",
		count:"Int",
		max:"fdp_pdp_max_fields",
		min:"fdp_pdp_min_fields",
		stddev:"fdp_pdp_stddev_fields",
		stddev_pop:"fdp_pdp_stddev_pop_fields",
		stddev_samp:"fdp_pdp_stddev_samp_fields",
		sum:"fdp_pdp_sum_fields",
		var_pop:"fdp_pdp_var_pop_fields",
		var_samp:"fdp_pdp_var_samp_fields",
		variance:"fdp_pdp_variance_fields"
	},
	fdp_pdp_avg_fields:{
		cursorId:"Float"
	},
	fdp_pdp_max_fields:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		venue:"String"
	},
	fdp_pdp_min_fields:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		venue:"String"
	},
	fdp_pdp_mutation_response:{
		affected_rows:"Int",
		returning:"fdp_pdp"
	},
	fdp_pdp_stddev_fields:{
		cursorId:"Float"
	},
	fdp_pdp_stddev_pop_fields:{
		cursorId:"Float"
	},
	fdp_pdp_stddev_samp_fields:{
		cursorId:"Float"
	},
	fdp_pdp_sum_fields:{
		cursorId:"bigint"
	},
	fdp_pdp_var_pop_fields:{
		cursorId:"Float"
	},
	fdp_pdp_var_samp_fields:{
		cursorId:"Float"
	},
	fdp_pdp_variance_fields:{
		cursorId:"Float"
	},
	genesis:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		email_id:"String",
		id:"uuid",
		isVerified:"String",
		name:"String",
		phone:"String",
		role:"String",
		status:"STATUS_enum",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_aggregate:{
		aggregate:"genesis_aggregate_fields",
		nodes:"genesis"
	},
	genesis_aggregate_fields:{
		avg:"genesis_avg_fields",
		count:"Int",
		max:"genesis_max_fields",
		min:"genesis_min_fields",
		stddev:"genesis_stddev_fields",
		stddev_pop:"genesis_stddev_pop_fields",
		stddev_samp:"genesis_stddev_samp_fields",
		sum:"genesis_sum_fields",
		var_pop:"genesis_var_pop_fields",
		var_samp:"genesis_var_samp_fields",
		variance:"genesis_variance_fields"
	},
	genesis_avg_fields:{
		cursorId:"Float"
	},
	genesis_max_fields:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		email_id:"String",
		id:"uuid",
		isVerified:"String",
		name:"String",
		phone:"String",
		role:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_min_fields:{
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		email_id:"String",
		id:"uuid",
		isVerified:"String",
		name:"String",
		phone:"String",
		role:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	genesis_mutation_response:{
		affected_rows:"Int",
		returning:"genesis"
	},
	genesis_stddev_fields:{
		cursorId:"Float"
	},
	genesis_stddev_pop_fields:{
		cursorId:"Float"
	},
	genesis_stddev_samp_fields:{
		cursorId:"Float"
	},
	genesis_sum_fields:{
		cursorId:"bigint"
	},
	genesis_var_pop_fields:{
		cursorId:"Float"
	},
	genesis_var_samp_fields:{
		cursorId:"Float"
	},
	genesis_variance_fields:{
		cursorId:"Float"
	},
	institute:{
		address:"String",
		city:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		e_governances:"e_governance",
		e_governances_aggregate:"e_governance_aggregate",
		faculties:"faculty",
		faculties_aggregate:"faculty_aggregate",
		faculty_fundings:"faculty_funding",
		faculty_fundings_aggregate:"faculty_funding_aggregate",
		fdp_pdps:"fdp_pdp",
		fdp_pdps_aggregate:"fdp_pdp_aggregate",
		id:"uuid",
		institute_fundings:"institute_funding",
		institute_fundings_aggregate:"institute_funding_aggregate",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		status:"STATUS_enum",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	institute_aggregate:{
		aggregate:"institute_aggregate_fields",
		nodes:"institute"
	},
	institute_aggregate_fields:{
		avg:"institute_avg_fields",
		count:"Int",
		max:"institute_max_fields",
		min:"institute_min_fields",
		stddev:"institute_stddev_fields",
		stddev_pop:"institute_stddev_pop_fields",
		stddev_samp:"institute_stddev_samp_fields",
		sum:"institute_sum_fields",
		var_pop:"institute_var_pop_fields",
		var_samp:"institute_var_samp_fields",
		variance:"institute_variance_fields"
	},
	institute_avg_fields:{
		cursorId:"Float"
	},
	institute_funding:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute:"institute",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		status:"STATUS_enum",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_aggregate:{
		aggregate:"institute_funding_aggregate_fields",
		nodes:"institute_funding"
	},
	institute_funding_aggregate_fields:{
		avg:"institute_funding_avg_fields",
		count:"Int",
		max:"institute_funding_max_fields",
		min:"institute_funding_min_fields",
		stddev:"institute_funding_stddev_fields",
		stddev_pop:"institute_funding_stddev_pop_fields",
		stddev_samp:"institute_funding_stddev_samp_fields",
		sum:"institute_funding_sum_fields",
		var_pop:"institute_funding_var_pop_fields",
		var_samp:"institute_funding_var_samp_fields",
		variance:"institute_funding_variance_fields"
	},
	institute_funding_avg_fields:{
		cursorId:"Float"
	},
	institute_funding_max_fields:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_min_fields:{
		amount:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid"
	},
	institute_funding_mutation_response:{
		affected_rows:"Int",
		returning:"institute_funding"
	},
	institute_funding_stddev_fields:{
		cursorId:"Float"
	},
	institute_funding_stddev_pop_fields:{
		cursorId:"Float"
	},
	institute_funding_stddev_samp_fields:{
		cursorId:"Float"
	},
	institute_funding_sum_fields:{
		cursorId:"bigint"
	},
	institute_funding_var_pop_fields:{
		cursorId:"Float"
	},
	institute_funding_var_samp_fields:{
		cursorId:"Float"
	},
	institute_funding_variance_fields:{
		cursorId:"Float"
	},
	institute_max_fields:{
		address:"String",
		city:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		id:"uuid",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	institute_min_fields:{
		address:"String",
		city:"String",
		createdAt:"timestamptz",
		createdById:"uuid",
		cursorId:"bigint",
		date_of_establishment:"date",
		id:"uuid",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		type:"String",
		updatedAt:"timestamptz",
		updatedById:"uuid",
		website:"String"
	},
	institute_mutation_response:{
		affected_rows:"Int",
		returning:"institute"
	},
	institute_stddev_fields:{
		cursorId:"Float"
	},
	institute_stddev_pop_fields:{
		cursorId:"Float"
	},
	institute_stddev_samp_fields:{
		cursorId:"Float"
	},
	institute_sum_fields:{
		cursorId:"bigint"
	},
	institute_var_pop_fields:{
		cursorId:"Float"
	},
	institute_var_samp_fields:{
		cursorId:"Float"
	},
	institute_variance_fields:{
		cursorId:"Float"
	},
	mutation_root:{
		delete_STATUS:"STATUS_mutation_response",
		delete_STATUS_by_pk:"STATUS",
		delete_e_governance:"e_governance_mutation_response",
		delete_e_governance_by_pk:"e_governance",
		delete_faculty:"faculty_mutation_response",
		delete_faculty_by_pk:"faculty",
		delete_faculty_funding:"faculty_funding_mutation_response",
		delete_faculty_funding_by_pk:"faculty_funding",
		delete_fdp_pdp:"fdp_pdp_mutation_response",
		delete_fdp_pdp_by_pk:"fdp_pdp",
		delete_genesis:"genesis_mutation_response",
		delete_genesis_by_pk:"genesis",
		delete_institute:"institute_mutation_response",
		delete_institute_by_pk:"institute",
		delete_institute_funding:"institute_funding_mutation_response",
		delete_institute_funding_by_pk:"institute_funding",
		insert_STATUS:"STATUS_mutation_response",
		insert_STATUS_one:"STATUS",
		insert_e_governance:"e_governance_mutation_response",
		insert_e_governance_one:"e_governance",
		insert_faculty:"faculty_mutation_response",
		insert_faculty_funding:"faculty_funding_mutation_response",
		insert_faculty_funding_one:"faculty_funding",
		insert_faculty_one:"faculty",
		insert_fdp_pdp:"fdp_pdp_mutation_response",
		insert_fdp_pdp_one:"fdp_pdp",
		insert_genesis:"genesis_mutation_response",
		insert_genesis_one:"genesis",
		insert_institute:"institute_mutation_response",
		insert_institute_funding:"institute_funding_mutation_response",
		insert_institute_funding_one:"institute_funding",
		insert_institute_one:"institute",
		update_STATUS:"STATUS_mutation_response",
		update_STATUS_by_pk:"STATUS",
		update_STATUS_many:"STATUS_mutation_response",
		update_e_governance:"e_governance_mutation_response",
		update_e_governance_by_pk:"e_governance",
		update_e_governance_many:"e_governance_mutation_response",
		update_faculty:"faculty_mutation_response",
		update_faculty_by_pk:"faculty",
		update_faculty_funding:"faculty_funding_mutation_response",
		update_faculty_funding_by_pk:"faculty_funding",
		update_faculty_funding_many:"faculty_funding_mutation_response",
		update_faculty_many:"faculty_mutation_response",
		update_fdp_pdp:"fdp_pdp_mutation_response",
		update_fdp_pdp_by_pk:"fdp_pdp",
		update_fdp_pdp_many:"fdp_pdp_mutation_response",
		update_genesis:"genesis_mutation_response",
		update_genesis_by_pk:"genesis",
		update_genesis_many:"genesis_mutation_response",
		update_institute:"institute_mutation_response",
		update_institute_by_pk:"institute",
		update_institute_funding:"institute_funding_mutation_response",
		update_institute_funding_by_pk:"institute_funding",
		update_institute_funding_many:"institute_funding_mutation_response",
		update_institute_many:"institute_mutation_response"
	},
	query_root:{
		STATUS:"STATUS",
		STATUS_aggregate:"STATUS_aggregate",
		STATUS_by_pk:"STATUS",
		e_governance:"e_governance",
		e_governance_aggregate:"e_governance_aggregate",
		e_governance_by_pk:"e_governance",
		faculty:"faculty",
		faculty_aggregate:"faculty_aggregate",
		faculty_by_pk:"faculty",
		faculty_funding:"faculty_funding",
		faculty_funding_aggregate:"faculty_funding_aggregate",
		faculty_funding_by_pk:"faculty_funding",
		fdp_pdp:"fdp_pdp",
		fdp_pdp_aggregate:"fdp_pdp_aggregate",
		fdp_pdp_by_pk:"fdp_pdp",
		genesis:"genesis",
		genesis_aggregate:"genesis_aggregate",
		genesis_by_pk:"genesis",
		institute:"institute",
		institute_aggregate:"institute_aggregate",
		institute_by_pk:"institute",
		institute_funding:"institute_funding",
		institute_funding_aggregate:"institute_funding_aggregate",
		institute_funding_by_pk:"institute_funding"
	},
	subscription_root:{
		STATUS:"STATUS",
		STATUS_aggregate:"STATUS_aggregate",
		STATUS_by_pk:"STATUS",
		STATUS_stream:"STATUS",
		e_governance:"e_governance",
		e_governance_aggregate:"e_governance_aggregate",
		e_governance_by_pk:"e_governance",
		e_governance_stream:"e_governance",
		faculty:"faculty",
		faculty_aggregate:"faculty_aggregate",
		faculty_by_pk:"faculty",
		faculty_funding:"faculty_funding",
		faculty_funding_aggregate:"faculty_funding_aggregate",
		faculty_funding_by_pk:"faculty_funding",
		faculty_funding_stream:"faculty_funding",
		faculty_stream:"faculty",
		fdp_pdp:"fdp_pdp",
		fdp_pdp_aggregate:"fdp_pdp_aggregate",
		fdp_pdp_by_pk:"fdp_pdp",
		fdp_pdp_stream:"fdp_pdp",
		genesis:"genesis",
		genesis_aggregate:"genesis_aggregate",
		genesis_by_pk:"genesis",
		genesis_stream:"genesis",
		institute:"institute",
		institute_aggregate:"institute_aggregate",
		institute_by_pk:"institute",
		institute_funding:"institute_funding",
		institute_funding_aggregate:"institute_funding_aggregate",
		institute_funding_by_pk:"institute_funding",
		institute_funding_stream:"institute_funding",
		institute_stream:"institute"
	},
	timestamptz: `scalar.timestamptz` as const,
	uuid: `scalar.uuid` as const
}

export const Ops = {
query: "query_root" as const,
	mutation: "mutation_root" as const,
	subscription: "subscription_root" as const
}