/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Boolean_comparison_exp:{

	},
	EGovernance_aggregate_fields:{
		count:{
			columns:"EGovernance_select_column"
		}
	},
	EGovernance_bool_exp:{
		_and:"EGovernance_bool_exp",
		_not:"EGovernance_bool_exp",
		_or:"EGovernance_bool_exp",
		address:"String_comparison_exp",
		area:"String_comparison_exp",
		createdById:"uuid_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		cursorId:"String_comparison_exp",
		description:"String_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		phone_no:"String_comparison_exp",
		service_end_date:"date_comparison_exp",
		service_start_date:"date_comparison_exp",
		status:"String_comparison_exp",
		total_amount:"String_comparison_exp",
		updatedById:"uuid_comparison_exp",
		updated_at:"timestamptz_comparison_exp",
		website:"String_comparison_exp"
	},
	EGovernance_constraint: "enum" as const,
	EGovernance_insert_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	EGovernance_on_conflict:{
		constraint:"EGovernance_constraint",
		update_columns:"EGovernance_update_column",
		where:"EGovernance_bool_exp"
	},
	EGovernance_order_by:{
		address:"order_by",
		area:"order_by",
		createdById:"order_by",
		created_at:"order_by",
		cursorId:"order_by",
		description:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		phone_no:"order_by",
		service_end_date:"order_by",
		service_start_date:"order_by",
		status:"order_by",
		total_amount:"order_by",
		updatedById:"order_by",
		updated_at:"order_by",
		website:"order_by"
	},
	EGovernance_pk_columns_input:{
		id:"uuid"
	},
	EGovernance_select_column: "enum" as const,
	EGovernance_set_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	EGovernance_stream_cursor_input:{
		initial_value:"EGovernance_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	EGovernance_stream_cursor_value_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		service_end_date:"date",
		service_start_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	EGovernance_update_column: "enum" as const,
	EGovernance_updates:{
		_set:"EGovernance_set_input",
		where:"EGovernance_bool_exp"
	},
	FacultyFunding_aggregate_fields:{
		count:{
			columns:"FacultyFunding_select_column"
		}
	},
	FacultyFunding_bool_exp:{
		_and:"FacultyFunding_bool_exp",
		_not:"FacultyFunding_bool_exp",
		_or:"FacultyFunding_bool_exp",
		amount:"String_comparison_exp",
		createdById:"uuid_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		cursorId:"String_comparison_exp",
		faculty_id:"uuid_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute_id:"uuid_comparison_exp",
		nature:"String_comparison_exp",
		status:"String_comparison_exp",
		transaction_date:"date_comparison_exp",
		transaction_type:"String_comparison_exp",
		type:"String_comparison_exp",
		updatedById:"uuid_comparison_exp",
		updated_at:"timestamptz_comparison_exp"
	},
	FacultyFunding_constraint: "enum" as const,
	FacultyFunding_insert_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_on_conflict:{
		constraint:"FacultyFunding_constraint",
		update_columns:"FacultyFunding_update_column",
		where:"FacultyFunding_bool_exp"
	},
	FacultyFunding_order_by:{
		amount:"order_by",
		createdById:"order_by",
		created_at:"order_by",
		cursorId:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		nature:"order_by",
		status:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedById:"order_by",
		updated_at:"order_by"
	},
	FacultyFunding_pk_columns_input:{
		id:"uuid"
	},
	FacultyFunding_select_column: "enum" as const,
	FacultyFunding_set_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_stream_cursor_input:{
		initial_value:"FacultyFunding_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	FacultyFunding_stream_cursor_value_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_update_column: "enum" as const,
	FacultyFunding_updates:{
		_set:"FacultyFunding_set_input",
		where:"FacultyFunding_bool_exp"
	},
	Faculty_aggregate_fields:{
		count:{
			columns:"Faculty_select_column"
		}
	},
	Faculty_bool_exp:{
		_and:"Faculty_bool_exp",
		_not:"Faculty_bool_exp",
		_or:"Faculty_bool_exp",
		address:"String_comparison_exp",
		cast:"String_comparison_exp",
		createdById:"uuid_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		cursorId:"String_comparison_exp",
		date_of_joining:"date_comparison_exp",
		designation:"String_comparison_exp",
		dob:"date_comparison_exp",
		email_id:"String_comparison_exp",
		experience:"String_comparison_exp",
		gender:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute_id:"uuid_comparison_exp",
		job_type:"String_comparison_exp",
		minority:"String_comparison_exp",
		name:"String_comparison_exp",
		pan_card_no:"String_comparison_exp",
		phone:"String_comparison_exp",
		qualification:"String_comparison_exp",
		section:"String_comparison_exp",
		staff_type:"String_comparison_exp",
		status:"String_comparison_exp",
		status_of_approval:"String_comparison_exp",
		updatedById:"uuid_comparison_exp",
		updated_at:"timestamptz_comparison_exp"
	},
	Faculty_constraint: "enum" as const,
	Faculty_insert_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_of_joining:"date",
		dob:"date",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	Faculty_on_conflict:{
		constraint:"Faculty_constraint",
		update_columns:"Faculty_update_column",
		where:"Faculty_bool_exp"
	},
	Faculty_order_by:{
		address:"order_by",
		cast:"order_by",
		createdById:"order_by",
		created_at:"order_by",
		cursorId:"order_by",
		date_of_joining:"order_by",
		designation:"order_by",
		dob:"order_by",
		email_id:"order_by",
		experience:"order_by",
		gender:"order_by",
		id:"order_by",
		institute_id:"order_by",
		job_type:"order_by",
		minority:"order_by",
		name:"order_by",
		pan_card_no:"order_by",
		phone:"order_by",
		qualification:"order_by",
		section:"order_by",
		staff_type:"order_by",
		status:"order_by",
		status_of_approval:"order_by",
		updatedById:"order_by",
		updated_at:"order_by"
	},
	Faculty_pk_columns_input:{
		id:"uuid"
	},
	Faculty_select_column: "enum" as const,
	Faculty_set_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_of_joining:"date",
		dob:"date",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	Faculty_stream_cursor_input:{
		initial_value:"Faculty_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	Faculty_stream_cursor_value_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_of_joining:"date",
		dob:"date",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	Faculty_update_column: "enum" as const,
	Faculty_updates:{
		_set:"Faculty_set_input",
		where:"Faculty_bool_exp"
	},
	FdpPdp_aggregate_fields:{
		count:{
			columns:"FdpPdp_select_column"
		}
	},
	FdpPdp_bool_exp:{
		_and:"FdpPdp_bool_exp",
		_not:"FdpPdp_bool_exp",
		_or:"FdpPdp_bool_exp",
		createdById:"uuid_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		cursorId:"String_comparison_exp",
		date_from:"date_comparison_exp",
		date_to:"date_comparison_exp",
		description:"String_comparison_exp",
		faculty_id:"uuid_comparison_exp",
		file:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		nature:"String_comparison_exp",
		status:"String_comparison_exp",
		type:"String_comparison_exp",
		updatedById:"uuid_comparison_exp",
		updated_at:"timestamptz_comparison_exp",
		venue:"String_comparison_exp"
	},
	FdpPdp_constraint: "enum" as const,
	FdpPdp_insert_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_from:"date",
		date_to:"date",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FdpPdp_on_conflict:{
		constraint:"FdpPdp_constraint",
		update_columns:"FdpPdp_update_column",
		where:"FdpPdp_bool_exp"
	},
	FdpPdp_order_by:{
		createdById:"order_by",
		created_at:"order_by",
		cursorId:"order_by",
		date_from:"order_by",
		date_to:"order_by",
		description:"order_by",
		faculty_id:"order_by",
		file:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		nature:"order_by",
		status:"order_by",
		type:"order_by",
		updatedById:"order_by",
		updated_at:"order_by",
		venue:"order_by"
	},
	FdpPdp_pk_columns_input:{
		id:"uuid"
	},
	FdpPdp_select_column: "enum" as const,
	FdpPdp_set_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_from:"date",
		date_to:"date",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FdpPdp_stream_cursor_input:{
		initial_value:"FdpPdp_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	FdpPdp_stream_cursor_value_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		date_from:"date",
		date_to:"date",
		faculty_id:"uuid",
		id:"uuid",
		institute_id:"uuid",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FdpPdp_update_column: "enum" as const,
	FdpPdp_updates:{
		_set:"FdpPdp_set_input",
		where:"FdpPdp_bool_exp"
	},
	Genesis_aggregate_fields:{
		count:{
			columns:"Genesis_select_column"
		}
	},
	Genesis_bool_exp:{
		_and:"Genesis_bool_exp",
		_not:"Genesis_bool_exp",
		_or:"Genesis_bool_exp",
		created_at:"timestamp_comparison_exp",
		email_id:"String_comparison_exp",
		id:"uuid_comparison_exp",
		is_verified:"Boolean_comparison_exp",
		name:"String_comparison_exp",
		phone:"String_comparison_exp",
		role:"String_comparison_exp",
		updated_at:"timestamp_comparison_exp"
	},
	Genesis_constraint: "enum" as const,
	Genesis_insert_input:{
		created_at:"timestamp",
		id:"uuid",
		updated_at:"timestamp"
	},
	Genesis_on_conflict:{
		constraint:"Genesis_constraint",
		update_columns:"Genesis_update_column",
		where:"Genesis_bool_exp"
	},
	Genesis_order_by:{
		created_at:"order_by",
		email_id:"order_by",
		id:"order_by",
		is_verified:"order_by",
		name:"order_by",
		phone:"order_by",
		role:"order_by",
		updated_at:"order_by"
	},
	Genesis_pk_columns_input:{
		id:"uuid"
	},
	Genesis_select_column: "enum" as const,
	Genesis_set_input:{
		created_at:"timestamp",
		id:"uuid",
		updated_at:"timestamp"
	},
	Genesis_stream_cursor_input:{
		initial_value:"Genesis_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	Genesis_stream_cursor_value_input:{
		created_at:"timestamp",
		id:"uuid",
		updated_at:"timestamp"
	},
	Genesis_update_column: "enum" as const,
	Genesis_updates:{
		_set:"Genesis_set_input",
		where:"Genesis_bool_exp"
	},
	InstituteFunding_aggregate_fields:{
		count:{
			columns:"InstituteFunding_select_column"
		}
	},
	InstituteFunding_bool_exp:{
		_and:"InstituteFunding_bool_exp",
		_not:"InstituteFunding_bool_exp",
		_or:"InstituteFunding_bool_exp",
		amount:"String_comparison_exp",
		createdById:"uuid_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		cursorId:"String_comparison_exp",
		id:"uuid_comparison_exp",
		institute_id:"uuid_comparison_exp",
		name:"String_comparison_exp",
		purpose:"String_comparison_exp",
		status:"String_comparison_exp",
		transaction_date:"date_comparison_exp",
		transaction_type:"String_comparison_exp",
		type:"String_comparison_exp",
		updatedById:"uuid_comparison_exp",
		updated_at:"timestamptz_comparison_exp"
	},
	InstituteFunding_constraint: "enum" as const,
	InstituteFunding_insert_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_on_conflict:{
		constraint:"InstituteFunding_constraint",
		update_columns:"InstituteFunding_update_column",
		where:"InstituteFunding_bool_exp"
	},
	InstituteFunding_order_by:{
		amount:"order_by",
		createdById:"order_by",
		created_at:"order_by",
		cursorId:"order_by",
		id:"order_by",
		institute_id:"order_by",
		name:"order_by",
		purpose:"order_by",
		status:"order_by",
		transaction_date:"order_by",
		transaction_type:"order_by",
		type:"order_by",
		updatedById:"order_by",
		updated_at:"order_by"
	},
	InstituteFunding_pk_columns_input:{
		id:"uuid"
	},
	InstituteFunding_select_column: "enum" as const,
	InstituteFunding_set_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_stream_cursor_input:{
		initial_value:"InstituteFunding_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	InstituteFunding_stream_cursor_value_input:{
		createdById:"uuid",
		created_at:"timestamptz",
		id:"uuid",
		institute_id:"uuid",
		transaction_date:"date",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_update_column: "enum" as const,
	InstituteFunding_updates:{
		_set:"InstituteFunding_set_input",
		where:"InstituteFunding_bool_exp"
	},
	Institute_aggregate_fields:{
		count:{
			columns:"Institute_select_column"
		}
	},
	Institute_bool_exp:{
		_and:"Institute_bool_exp",
		_not:"Institute_bool_exp",
		_or:"Institute_bool_exp",
		address:"String_comparison_exp",
		city:"String_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		created_by_id:"uuid_comparison_exp",
		cursor_id:"String_comparison_exp",
		date_of_establishment:"date_comparison_exp",
		id:"uuid_comparison_exp",
		landmark:"String_comparison_exp",
		name:"String_comparison_exp",
		pin:"String_comparison_exp",
		state:"String_comparison_exp",
		type:"String_comparison_exp",
		updated_at:"timestamptz_comparison_exp",
		updated_by_id:"uuid_comparison_exp",
		website:"String_comparison_exp"
	},
	Institute_constraint: "enum" as const,
	Institute_insert_input:{
		created_at:"timestamptz",
		created_by_id:"uuid",
		date_of_establishment:"date",
		id:"uuid",
		updated_at:"timestamptz",
		updated_by_id:"uuid"
	},
	Institute_on_conflict:{
		constraint:"Institute_constraint",
		update_columns:"Institute_update_column",
		where:"Institute_bool_exp"
	},
	Institute_order_by:{
		address:"order_by",
		city:"order_by",
		created_at:"order_by",
		created_by_id:"order_by",
		cursor_id:"order_by",
		date_of_establishment:"order_by",
		id:"order_by",
		landmark:"order_by",
		name:"order_by",
		pin:"order_by",
		state:"order_by",
		type:"order_by",
		updated_at:"order_by",
		updated_by_id:"order_by",
		website:"order_by"
	},
	Institute_pk_columns_input:{
		id:"uuid"
	},
	Institute_select_column: "enum" as const,
	Institute_set_input:{
		created_at:"timestamptz",
		created_by_id:"uuid",
		date_of_establishment:"date",
		id:"uuid",
		updated_at:"timestamptz",
		updated_by_id:"uuid"
	},
	Institute_stream_cursor_input:{
		initial_value:"Institute_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	Institute_stream_cursor_value_input:{
		created_at:"timestamptz",
		created_by_id:"uuid",
		date_of_establishment:"date",
		id:"uuid",
		updated_at:"timestamptz",
		updated_by_id:"uuid"
	},
	Institute_update_column: "enum" as const,
	Institute_updates:{
		_set:"Institute_set_input",
		where:"Institute_bool_exp"
	},
	String_comparison_exp:{

	},
	cursor_ordering: "enum" as const,
	date: `scalar.date` as const,
	date_comparison_exp:{
		_eq:"date",
		_gt:"date",
		_gte:"date",
		_in:"date",
		_lt:"date",
		_lte:"date",
		_neq:"date",
		_nin:"date"
	},
	mutation_root:{
		delete_EGovernance:{
			where:"EGovernance_bool_exp"
		},
		delete_EGovernance_by_pk:{
			id:"uuid"
		},
		delete_Faculty:{
			where:"Faculty_bool_exp"
		},
		delete_FacultyFunding:{
			where:"FacultyFunding_bool_exp"
		},
		delete_FacultyFunding_by_pk:{
			id:"uuid"
		},
		delete_Faculty_by_pk:{
			id:"uuid"
		},
		delete_FdpPdp:{
			where:"FdpPdp_bool_exp"
		},
		delete_FdpPdp_by_pk:{
			id:"uuid"
		},
		delete_Genesis:{
			where:"Genesis_bool_exp"
		},
		delete_Genesis_by_pk:{
			id:"uuid"
		},
		delete_Institute:{
			where:"Institute_bool_exp"
		},
		delete_InstituteFunding:{
			where:"InstituteFunding_bool_exp"
		},
		delete_InstituteFunding_by_pk:{
			id:"uuid"
		},
		delete_Institute_by_pk:{
			id:"uuid"
		},
		insert_EGovernance:{
			objects:"EGovernance_insert_input",
			on_conflict:"EGovernance_on_conflict"
		},
		insert_EGovernance_one:{
			object:"EGovernance_insert_input",
			on_conflict:"EGovernance_on_conflict"
		},
		insert_Faculty:{
			objects:"Faculty_insert_input",
			on_conflict:"Faculty_on_conflict"
		},
		insert_FacultyFunding:{
			objects:"FacultyFunding_insert_input",
			on_conflict:"FacultyFunding_on_conflict"
		},
		insert_FacultyFunding_one:{
			object:"FacultyFunding_insert_input",
			on_conflict:"FacultyFunding_on_conflict"
		},
		insert_Faculty_one:{
			object:"Faculty_insert_input",
			on_conflict:"Faculty_on_conflict"
		},
		insert_FdpPdp:{
			objects:"FdpPdp_insert_input",
			on_conflict:"FdpPdp_on_conflict"
		},
		insert_FdpPdp_one:{
			object:"FdpPdp_insert_input",
			on_conflict:"FdpPdp_on_conflict"
		},
		insert_Genesis:{
			objects:"Genesis_insert_input",
			on_conflict:"Genesis_on_conflict"
		},
		insert_Genesis_one:{
			object:"Genesis_insert_input",
			on_conflict:"Genesis_on_conflict"
		},
		insert_Institute:{
			objects:"Institute_insert_input",
			on_conflict:"Institute_on_conflict"
		},
		insert_InstituteFunding:{
			objects:"InstituteFunding_insert_input",
			on_conflict:"InstituteFunding_on_conflict"
		},
		insert_InstituteFunding_one:{
			object:"InstituteFunding_insert_input",
			on_conflict:"InstituteFunding_on_conflict"
		},
		insert_Institute_one:{
			object:"Institute_insert_input",
			on_conflict:"Institute_on_conflict"
		},
		update_EGovernance:{
			_set:"EGovernance_set_input",
			where:"EGovernance_bool_exp"
		},
		update_EGovernance_by_pk:{
			_set:"EGovernance_set_input",
			pk_columns:"EGovernance_pk_columns_input"
		},
		update_EGovernance_many:{
			updates:"EGovernance_updates"
		},
		update_Faculty:{
			_set:"Faculty_set_input",
			where:"Faculty_bool_exp"
		},
		update_FacultyFunding:{
			_set:"FacultyFunding_set_input",
			where:"FacultyFunding_bool_exp"
		},
		update_FacultyFunding_by_pk:{
			_set:"FacultyFunding_set_input",
			pk_columns:"FacultyFunding_pk_columns_input"
		},
		update_FacultyFunding_many:{
			updates:"FacultyFunding_updates"
		},
		update_Faculty_by_pk:{
			_set:"Faculty_set_input",
			pk_columns:"Faculty_pk_columns_input"
		},
		update_Faculty_many:{
			updates:"Faculty_updates"
		},
		update_FdpPdp:{
			_set:"FdpPdp_set_input",
			where:"FdpPdp_bool_exp"
		},
		update_FdpPdp_by_pk:{
			_set:"FdpPdp_set_input",
			pk_columns:"FdpPdp_pk_columns_input"
		},
		update_FdpPdp_many:{
			updates:"FdpPdp_updates"
		},
		update_Genesis:{
			_set:"Genesis_set_input",
			where:"Genesis_bool_exp"
		},
		update_Genesis_by_pk:{
			_set:"Genesis_set_input",
			pk_columns:"Genesis_pk_columns_input"
		},
		update_Genesis_many:{
			updates:"Genesis_updates"
		},
		update_Institute:{
			_set:"Institute_set_input",
			where:"Institute_bool_exp"
		},
		update_InstituteFunding:{
			_set:"InstituteFunding_set_input",
			where:"InstituteFunding_bool_exp"
		},
		update_InstituteFunding_by_pk:{
			_set:"InstituteFunding_set_input",
			pk_columns:"InstituteFunding_pk_columns_input"
		},
		update_InstituteFunding_many:{
			updates:"InstituteFunding_updates"
		},
		update_Institute_by_pk:{
			_set:"Institute_set_input",
			pk_columns:"Institute_pk_columns_input"
		},
		update_Institute_many:{
			updates:"Institute_updates"
		}
	},
	order_by: "enum" as const,
	query_root:{
		EGovernance:{
			distinct_on:"EGovernance_select_column",
			order_by:"EGovernance_order_by",
			where:"EGovernance_bool_exp"
		},
		EGovernance_aggregate:{
			distinct_on:"EGovernance_select_column",
			order_by:"EGovernance_order_by",
			where:"EGovernance_bool_exp"
		},
		EGovernance_by_pk:{
			id:"uuid"
		},
		Faculty:{
			distinct_on:"Faculty_select_column",
			order_by:"Faculty_order_by",
			where:"Faculty_bool_exp"
		},
		FacultyFunding:{
			distinct_on:"FacultyFunding_select_column",
			order_by:"FacultyFunding_order_by",
			where:"FacultyFunding_bool_exp"
		},
		FacultyFunding_aggregate:{
			distinct_on:"FacultyFunding_select_column",
			order_by:"FacultyFunding_order_by",
			where:"FacultyFunding_bool_exp"
		},
		FacultyFunding_by_pk:{
			id:"uuid"
		},
		Faculty_aggregate:{
			distinct_on:"Faculty_select_column",
			order_by:"Faculty_order_by",
			where:"Faculty_bool_exp"
		},
		Faculty_by_pk:{
			id:"uuid"
		},
		FdpPdp:{
			distinct_on:"FdpPdp_select_column",
			order_by:"FdpPdp_order_by",
			where:"FdpPdp_bool_exp"
		},
		FdpPdp_aggregate:{
			distinct_on:"FdpPdp_select_column",
			order_by:"FdpPdp_order_by",
			where:"FdpPdp_bool_exp"
		},
		FdpPdp_by_pk:{
			id:"uuid"
		},
		Genesis:{
			distinct_on:"Genesis_select_column",
			order_by:"Genesis_order_by",
			where:"Genesis_bool_exp"
		},
		Genesis_aggregate:{
			distinct_on:"Genesis_select_column",
			order_by:"Genesis_order_by",
			where:"Genesis_bool_exp"
		},
		Genesis_by_pk:{
			id:"uuid"
		},
		Institute:{
			distinct_on:"Institute_select_column",
			order_by:"Institute_order_by",
			where:"Institute_bool_exp"
		},
		InstituteFunding:{
			distinct_on:"InstituteFunding_select_column",
			order_by:"InstituteFunding_order_by",
			where:"InstituteFunding_bool_exp"
		},
		InstituteFunding_aggregate:{
			distinct_on:"InstituteFunding_select_column",
			order_by:"InstituteFunding_order_by",
			where:"InstituteFunding_bool_exp"
		},
		InstituteFunding_by_pk:{
			id:"uuid"
		},
		Institute_aggregate:{
			distinct_on:"Institute_select_column",
			order_by:"Institute_order_by",
			where:"Institute_bool_exp"
		},
		Institute_by_pk:{
			id:"uuid"
		}
	},
	subscription_root:{
		EGovernance:{
			distinct_on:"EGovernance_select_column",
			order_by:"EGovernance_order_by",
			where:"EGovernance_bool_exp"
		},
		EGovernance_aggregate:{
			distinct_on:"EGovernance_select_column",
			order_by:"EGovernance_order_by",
			where:"EGovernance_bool_exp"
		},
		EGovernance_by_pk:{
			id:"uuid"
		},
		EGovernance_stream:{
			cursor:"EGovernance_stream_cursor_input",
			where:"EGovernance_bool_exp"
		},
		Faculty:{
			distinct_on:"Faculty_select_column",
			order_by:"Faculty_order_by",
			where:"Faculty_bool_exp"
		},
		FacultyFunding:{
			distinct_on:"FacultyFunding_select_column",
			order_by:"FacultyFunding_order_by",
			where:"FacultyFunding_bool_exp"
		},
		FacultyFunding_aggregate:{
			distinct_on:"FacultyFunding_select_column",
			order_by:"FacultyFunding_order_by",
			where:"FacultyFunding_bool_exp"
		},
		FacultyFunding_by_pk:{
			id:"uuid"
		},
		FacultyFunding_stream:{
			cursor:"FacultyFunding_stream_cursor_input",
			where:"FacultyFunding_bool_exp"
		},
		Faculty_aggregate:{
			distinct_on:"Faculty_select_column",
			order_by:"Faculty_order_by",
			where:"Faculty_bool_exp"
		},
		Faculty_by_pk:{
			id:"uuid"
		},
		Faculty_stream:{
			cursor:"Faculty_stream_cursor_input",
			where:"Faculty_bool_exp"
		},
		FdpPdp:{
			distinct_on:"FdpPdp_select_column",
			order_by:"FdpPdp_order_by",
			where:"FdpPdp_bool_exp"
		},
		FdpPdp_aggregate:{
			distinct_on:"FdpPdp_select_column",
			order_by:"FdpPdp_order_by",
			where:"FdpPdp_bool_exp"
		},
		FdpPdp_by_pk:{
			id:"uuid"
		},
		FdpPdp_stream:{
			cursor:"FdpPdp_stream_cursor_input",
			where:"FdpPdp_bool_exp"
		},
		Genesis:{
			distinct_on:"Genesis_select_column",
			order_by:"Genesis_order_by",
			where:"Genesis_bool_exp"
		},
		Genesis_aggregate:{
			distinct_on:"Genesis_select_column",
			order_by:"Genesis_order_by",
			where:"Genesis_bool_exp"
		},
		Genesis_by_pk:{
			id:"uuid"
		},
		Genesis_stream:{
			cursor:"Genesis_stream_cursor_input",
			where:"Genesis_bool_exp"
		},
		Institute:{
			distinct_on:"Institute_select_column",
			order_by:"Institute_order_by",
			where:"Institute_bool_exp"
		},
		InstituteFunding:{
			distinct_on:"InstituteFunding_select_column",
			order_by:"InstituteFunding_order_by",
			where:"InstituteFunding_bool_exp"
		},
		InstituteFunding_aggregate:{
			distinct_on:"InstituteFunding_select_column",
			order_by:"InstituteFunding_order_by",
			where:"InstituteFunding_bool_exp"
		},
		InstituteFunding_by_pk:{
			id:"uuid"
		},
		InstituteFunding_stream:{
			cursor:"InstituteFunding_stream_cursor_input",
			where:"InstituteFunding_bool_exp"
		},
		Institute_aggregate:{
			distinct_on:"Institute_select_column",
			order_by:"Institute_order_by",
			where:"Institute_bool_exp"
		},
		Institute_by_pk:{
			id:"uuid"
		},
		Institute_stream:{
			cursor:"Institute_stream_cursor_input",
			where:"Institute_bool_exp"
		}
	},
	timestamp: `scalar.timestamp` as const,
	timestamp_comparison_exp:{
		_eq:"timestamp",
		_gt:"timestamp",
		_gte:"timestamp",
		_in:"timestamp",
		_lt:"timestamp",
		_lte:"timestamp",
		_neq:"timestamp",
		_nin:"timestamp"
	},
	timestamptz: `scalar.timestamptz` as const,
	timestamptz_comparison_exp:{
		_eq:"timestamptz",
		_gt:"timestamptz",
		_gte:"timestamptz",
		_in:"timestamptz",
		_lt:"timestamptz",
		_lte:"timestamptz",
		_neq:"timestamptz",
		_nin:"timestamptz"
	},
	uuid: `scalar.uuid` as const,
	uuid_comparison_exp:{
		_eq:"uuid",
		_gt:"uuid",
		_gte:"uuid",
		_in:"uuid",
		_lt:"uuid",
		_lte:"uuid",
		_neq:"uuid",
		_nin:"uuid"
	}
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	EGovernance:{
		address:"String",
		area:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		description:"String",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		status:"String",
		total_amount:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		website:"String"
	},
	EGovernance_aggregate:{
		aggregate:"EGovernance_aggregate_fields",
		nodes:"EGovernance"
	},
	EGovernance_aggregate_fields:{
		count:"Int",
		max:"EGovernance_max_fields",
		min:"EGovernance_min_fields"
	},
	EGovernance_max_fields:{
		address:"String",
		area:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		description:"String",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		status:"String",
		total_amount:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		website:"String"
	},
	EGovernance_min_fields:{
		address:"String",
		area:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		description:"String",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		phone_no:"String",
		service_end_date:"date",
		service_start_date:"date",
		status:"String",
		total_amount:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		website:"String"
	},
	EGovernance_mutation_response:{
		affected_rows:"Int",
		returning:"EGovernance"
	},
	Faculty:{
		address:"String",
		cast:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		gender:"String",
		id:"uuid",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status:"String",
		status_of_approval:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		nature:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_aggregate:{
		aggregate:"FacultyFunding_aggregate_fields",
		nodes:"FacultyFunding"
	},
	FacultyFunding_aggregate_fields:{
		count:"Int",
		max:"FacultyFunding_max_fields",
		min:"FacultyFunding_min_fields"
	},
	FacultyFunding_max_fields:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		nature:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_min_fields:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		nature:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	FacultyFunding_mutation_response:{
		affected_rows:"Int",
		returning:"FacultyFunding"
	},
	Faculty_aggregate:{
		aggregate:"Faculty_aggregate_fields",
		nodes:"Faculty"
	},
	Faculty_aggregate_fields:{
		count:"Int",
		max:"Faculty_max_fields",
		min:"Faculty_min_fields"
	},
	Faculty_max_fields:{
		address:"String",
		cast:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		gender:"String",
		id:"uuid",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status:"String",
		status_of_approval:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	Faculty_min_fields:{
		address:"String",
		cast:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_of_joining:"date",
		designation:"String",
		dob:"date",
		email_id:"String",
		experience:"String",
		gender:"String",
		id:"uuid",
		institute_id:"uuid",
		job_type:"String",
		minority:"String",
		name:"String",
		pan_card_no:"String",
		phone:"String",
		qualification:"String",
		section:"String",
		staff_type:"String",
		status:"String",
		status_of_approval:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	Faculty_mutation_response:{
		affected_rows:"Int",
		returning:"Faculty"
	},
	FdpPdp:{
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		status:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		venue:"String"
	},
	FdpPdp_aggregate:{
		aggregate:"FdpPdp_aggregate_fields",
		nodes:"FdpPdp"
	},
	FdpPdp_aggregate_fields:{
		count:"Int",
		max:"FdpPdp_max_fields",
		min:"FdpPdp_min_fields"
	},
	FdpPdp_max_fields:{
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		status:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		venue:"String"
	},
	FdpPdp_min_fields:{
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		date_from:"date",
		date_to:"date",
		description:"String",
		faculty_id:"uuid",
		file:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		nature:"String",
		status:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz",
		venue:"String"
	},
	FdpPdp_mutation_response:{
		affected_rows:"Int",
		returning:"FdpPdp"
	},
	Genesis:{
		created_at:"timestamp",
		email_id:"String",
		id:"uuid",
		is_verified:"Boolean",
		name:"String",
		phone:"String",
		role:"String",
		updated_at:"timestamp"
	},
	Genesis_aggregate:{
		aggregate:"Genesis_aggregate_fields",
		nodes:"Genesis"
	},
	Genesis_aggregate_fields:{
		count:"Int",
		max:"Genesis_max_fields",
		min:"Genesis_min_fields"
	},
	Genesis_max_fields:{
		created_at:"timestamp",
		email_id:"String",
		id:"uuid",
		name:"String",
		phone:"String",
		role:"String",
		updated_at:"timestamp"
	},
	Genesis_min_fields:{
		created_at:"timestamp",
		email_id:"String",
		id:"uuid",
		name:"String",
		phone:"String",
		role:"String",
		updated_at:"timestamp"
	},
	Genesis_mutation_response:{
		affected_rows:"Int",
		returning:"Genesis"
	},
	Institute:{
		address:"String",
		city:"String",
		created_at:"timestamptz",
		created_by_id:"uuid",
		cursor_id:"String",
		date_of_establishment:"date",
		id:"uuid",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		type:"String",
		updated_at:"timestamptz",
		updated_by_id:"uuid",
		website:"String"
	},
	InstituteFunding:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_aggregate:{
		aggregate:"InstituteFunding_aggregate_fields",
		nodes:"InstituteFunding"
	},
	InstituteFunding_aggregate_fields:{
		count:"Int",
		max:"InstituteFunding_max_fields",
		min:"InstituteFunding_min_fields"
	},
	InstituteFunding_max_fields:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_min_fields:{
		amount:"String",
		createdById:"uuid",
		created_at:"timestamptz",
		cursorId:"String",
		id:"uuid",
		institute_id:"uuid",
		name:"String",
		purpose:"String",
		status:"String",
		transaction_date:"date",
		transaction_type:"String",
		type:"String",
		updatedById:"uuid",
		updated_at:"timestamptz"
	},
	InstituteFunding_mutation_response:{
		affected_rows:"Int",
		returning:"InstituteFunding"
	},
	Institute_aggregate:{
		aggregate:"Institute_aggregate_fields",
		nodes:"Institute"
	},
	Institute_aggregate_fields:{
		count:"Int",
		max:"Institute_max_fields",
		min:"Institute_min_fields"
	},
	Institute_max_fields:{
		address:"String",
		city:"String",
		created_at:"timestamptz",
		created_by_id:"uuid",
		cursor_id:"String",
		date_of_establishment:"date",
		id:"uuid",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		type:"String",
		updated_at:"timestamptz",
		updated_by_id:"uuid",
		website:"String"
	},
	Institute_min_fields:{
		address:"String",
		city:"String",
		created_at:"timestamptz",
		created_by_id:"uuid",
		cursor_id:"String",
		date_of_establishment:"date",
		id:"uuid",
		landmark:"String",
		name:"String",
		pin:"String",
		state:"String",
		type:"String",
		updated_at:"timestamptz",
		updated_by_id:"uuid",
		website:"String"
	},
	Institute_mutation_response:{
		affected_rows:"Int",
		returning:"Institute"
	},
	date: `scalar.date` as const,
	mutation_root:{
		delete_EGovernance:"EGovernance_mutation_response",
		delete_EGovernance_by_pk:"EGovernance",
		delete_Faculty:"Faculty_mutation_response",
		delete_FacultyFunding:"FacultyFunding_mutation_response",
		delete_FacultyFunding_by_pk:"FacultyFunding",
		delete_Faculty_by_pk:"Faculty",
		delete_FdpPdp:"FdpPdp_mutation_response",
		delete_FdpPdp_by_pk:"FdpPdp",
		delete_Genesis:"Genesis_mutation_response",
		delete_Genesis_by_pk:"Genesis",
		delete_Institute:"Institute_mutation_response",
		delete_InstituteFunding:"InstituteFunding_mutation_response",
		delete_InstituteFunding_by_pk:"InstituteFunding",
		delete_Institute_by_pk:"Institute",
		insert_EGovernance:"EGovernance_mutation_response",
		insert_EGovernance_one:"EGovernance",
		insert_Faculty:"Faculty_mutation_response",
		insert_FacultyFunding:"FacultyFunding_mutation_response",
		insert_FacultyFunding_one:"FacultyFunding",
		insert_Faculty_one:"Faculty",
		insert_FdpPdp:"FdpPdp_mutation_response",
		insert_FdpPdp_one:"FdpPdp",
		insert_Genesis:"Genesis_mutation_response",
		insert_Genesis_one:"Genesis",
		insert_Institute:"Institute_mutation_response",
		insert_InstituteFunding:"InstituteFunding_mutation_response",
		insert_InstituteFunding_one:"InstituteFunding",
		insert_Institute_one:"Institute",
		update_EGovernance:"EGovernance_mutation_response",
		update_EGovernance_by_pk:"EGovernance",
		update_EGovernance_many:"EGovernance_mutation_response",
		update_Faculty:"Faculty_mutation_response",
		update_FacultyFunding:"FacultyFunding_mutation_response",
		update_FacultyFunding_by_pk:"FacultyFunding",
		update_FacultyFunding_many:"FacultyFunding_mutation_response",
		update_Faculty_by_pk:"Faculty",
		update_Faculty_many:"Faculty_mutation_response",
		update_FdpPdp:"FdpPdp_mutation_response",
		update_FdpPdp_by_pk:"FdpPdp",
		update_FdpPdp_many:"FdpPdp_mutation_response",
		update_Genesis:"Genesis_mutation_response",
		update_Genesis_by_pk:"Genesis",
		update_Genesis_many:"Genesis_mutation_response",
		update_Institute:"Institute_mutation_response",
		update_InstituteFunding:"InstituteFunding_mutation_response",
		update_InstituteFunding_by_pk:"InstituteFunding",
		update_InstituteFunding_many:"InstituteFunding_mutation_response",
		update_Institute_by_pk:"Institute",
		update_Institute_many:"Institute_mutation_response"
	},
	query_root:{
		EGovernance:"EGovernance",
		EGovernance_aggregate:"EGovernance_aggregate",
		EGovernance_by_pk:"EGovernance",
		Faculty:"Faculty",
		FacultyFunding:"FacultyFunding",
		FacultyFunding_aggregate:"FacultyFunding_aggregate",
		FacultyFunding_by_pk:"FacultyFunding",
		Faculty_aggregate:"Faculty_aggregate",
		Faculty_by_pk:"Faculty",
		FdpPdp:"FdpPdp",
		FdpPdp_aggregate:"FdpPdp_aggregate",
		FdpPdp_by_pk:"FdpPdp",
		Genesis:"Genesis",
		Genesis_aggregate:"Genesis_aggregate",
		Genesis_by_pk:"Genesis",
		Institute:"Institute",
		InstituteFunding:"InstituteFunding",
		InstituteFunding_aggregate:"InstituteFunding_aggregate",
		InstituteFunding_by_pk:"InstituteFunding",
		Institute_aggregate:"Institute_aggregate",
		Institute_by_pk:"Institute"
	},
	subscription_root:{
		EGovernance:"EGovernance",
		EGovernance_aggregate:"EGovernance_aggregate",
		EGovernance_by_pk:"EGovernance",
		EGovernance_stream:"EGovernance",
		Faculty:"Faculty",
		FacultyFunding:"FacultyFunding",
		FacultyFunding_aggregate:"FacultyFunding_aggregate",
		FacultyFunding_by_pk:"FacultyFunding",
		FacultyFunding_stream:"FacultyFunding",
		Faculty_aggregate:"Faculty_aggregate",
		Faculty_by_pk:"Faculty",
		Faculty_stream:"Faculty",
		FdpPdp:"FdpPdp",
		FdpPdp_aggregate:"FdpPdp_aggregate",
		FdpPdp_by_pk:"FdpPdp",
		FdpPdp_stream:"FdpPdp",
		Genesis:"Genesis",
		Genesis_aggregate:"Genesis_aggregate",
		Genesis_by_pk:"Genesis",
		Genesis_stream:"Genesis",
		Institute:"Institute",
		InstituteFunding:"InstituteFunding",
		InstituteFunding_aggregate:"InstituteFunding_aggregate",
		InstituteFunding_by_pk:"InstituteFunding",
		InstituteFunding_stream:"InstituteFunding",
		Institute_aggregate:"Institute_aggregate",
		Institute_by_pk:"Institute",
		Institute_stream:"Institute"
	},
	timestamp: `scalar.timestamp` as const,
	timestamptz: `scalar.timestamptz` as const,
	uuid: `scalar.uuid` as const
}

export const Ops = {
query: "query_root" as const,
	mutation: "mutation_root" as const,
	subscription: "subscription_root" as const
}